#%RAML 1.0 Library
types:
  insertBankData : !include ../dataTypes/insert-dataType.raml
  updateBankData : !include ../dataTypes/update-dataType.raml
traits:
  headers : !include ../exchange_modules/d12a3ea2-4e95-48a2-8b8d-d8a4a518f922/common-code/1.0.1/common-code.raml
  error code : !include exchange_modules/d12a3ea2-4e95-48a2-8b8d-d8a4a518f922/common-code/1.0.1/common-code.raml