[{
"id": 1234,
"bankName": "Martin's Savings Account",
"branchName" : "Panjagutta",
"accountNumber": "00007604",
"accountType": "Account",
"primaryAccountOwner": "b7c4eddf-9c67-11eb-b4c8-0233bdd64096",
"accountStatus": "OPEN",
"accountBalance": 1.2,
"availableBalance": 1.2,
"accountCurrency": "USD",
"accountLabel": "Rainy Day",
"interestRate": 0.25,
"taxIdentificationNumber": "012345678",
"openedDate": "2020-03-15",
"address":
{
"country": "United States of America",
"city": "San Francisco",
"zip_code": "53703",
"state": "California",
"address_line_1": "1855 Folsom Street"
}
},{
"id": 1235,
"bankName": "Martin's Savings Account",
"branchName" : "Koti",
"accountNumber": "00007605",
"accountType": "Account",
"primaryAccountOwner": "b7c4eddf-9c67-11eb-b4c8-0233bdd64097",
"accountStatus": "OPEN",
"accountBalance": 1.3,
"availableBalance": 1.3,
"accountCurrency": "USD",
"accountLabel": "Rainy Day",
"interestRate": 0.25,
"taxIdentificationNumber": "012345679",
"openedDate": "2020-03-15",
"address":
{
"country": "United States of America",
"city": "San Francisco",
"zip_code": "53703",
"state": "California",
"address_line_1": "1855 Folsom Street"
}
}]